spring:
  application:
    name: hdfc-life-policy-ledger
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
