CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_no VARCHAR(20) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    product_type VARCHAR(20) NOT NULL CHECK (product_type IN ('TERM', 'ULIP', 'ENDOWMENT')),
    base_premium INTEGER NOT NULL CHECK (base_premium > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('Active', 'Lapsed', 'Pending')),
    CONSTRAINT fk_policies_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_no VARCHAR(20) NOT NULL UNIQUE,
    policy_id BIGINT NOT NULL,
    amount INTEGER NOT NULL CHECK (amount > 0),
    urgency VARCHAR(10) NOT NULL CHECK (urgency IN ('HIGH', 'MEDIUM', 'LOW')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('SUBMITTED', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_claims_policy
        FOREIGN KEY (policy_id) REFERENCES policies(id)
);

CREATE TABLE riders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE policy_riders (
    policy_id BIGINT NOT NULL,
    rider_id BIGINT NOT NULL,
    PRIMARY KEY (policy_id, rider_id),
    CONSTRAINT fk_policy_riders_policy
        FOREIGN KEY (policy_id) REFERENCES policies(id),
    CONSTRAINT fk_policy_riders_rider
        FOREIGN KEY (rider_id) REFERENCES riders(id)
);
